### ISSUE TITLE
每次回答会携带上次回答的内容

### ISSUE THREAD

**Issue by VectorZhao** [Ink-Osier/PandoraToV1Api#1]
域名反代http://ip:50011, 将其添加到one-api的自定义代理中，fk token, gpt-4-s模型映射为gpt-4-vision-preview

![image](https://github.com/Ink-Osier/PandoraToV1Api/assets/16644993/5140ed68-9441-4093-842f-c5638a9f8ca9)

**Comment by VectorZhao** [comment]
看日志，每次聊天，返回内容结束后便会删除会话。而且图片无法正常显示，日志中出现json解析错误的提示

**Comment by VectorZhao** [comment]
![image](https://github.com/Ink-Osier/PandoraToV1Api/assets/16644993/f8be6e7f-5105-4d3f-b346-2190e328be82)
![image](https://github.com/Ink-Osier/PandoraToV1Api/assets/16644993/201724b8-e0e0-450e-bdb0-c5f9c66ce63c)
logs
`pandoratov1api-backend-to-api-1  | 129.150.52.237 - - [14/Dec/2023:05:49:50 +0000] "OPTIONS /v1/chat/completions HTTP/1.1" 200 0 "next-web的https地址" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"`

**Comment by Ink-Osier** [comment]
已修复重复回复的问题并初步修复了图片生成的问题，可以升级最新版再试试
