### ISSUE TITLE
好项目，经测试在Kerwin1202/chatgpt-web的项目中也实现了用gpt-4-mobile模型来画图的功能。

### ISSUE THREAD

**Issue by nanbei-zhuge** [Ink-Osier/PandoraToV1Api#14]
感谢大佬，感谢始皇，感谢Kerwin1202
https://github.com/Kerwin1202/chatgpt-web/issues/391

**Comment by nanbei-zhuge** [comment]
是不是也应该加个类似proxy_api_prefix的，可自定义的后缀，不然被扫到额度很快就见底了

**Comment by Ink-Osier** [comment]
> 是不是也应该加个类似proxy_api_prefix的，可自定义的后缀，不然被扫到额度很快就见底了

可以，后续版本会加上

**Comment by Ink-Osier** [comment]
> 是不是也应该加个类似proxy_api_prefix的，可自定义的后缀，不然被扫到额度很快就见底了

已支持
