### ISSUE TITLE
UPLOAD_BASE_URL 是什么？

### ISSUE THREAD

**Issue by GtxFury** [Ink-Osier/PandoraToV1Api#15]
请教UPLOAD_BASE_URL是什么，不配置能否使用画图？有没有参考的文档或者案例

**Comment by Ink-Osier** [comment]
必须要配置画图才能正常使用，配置为该项目的公网访问地址

**Comment by GtxFury** [comment]
感谢

**Comment by Ink-Osier** [comment]
客气

**Comment by GtxFury** [comment]
请问能支持pool tokens pk吗，fk只能单个账号，pk可以多账号轮询

**Comment by Ink-Osier** [comment]
是否支持pk取决于PandoraNext的backend-api是否支持pk，目前我测试还没成功过，欢迎测试一下然后反馈结果，可能是我pk生成的有问题

**Comment by Ink-Osier** [comment]
这个fk和pk在本项目里没有做任何处理是直接转发给PandoraNext的backend-api的

**Comment by GtxFury** [comment]
我实测了不行，但是换成fk正常

**Comment by Ink-Osier** [comment]
那应该就是不行，可以考虑再部署一个one-api，效果也是差不多的

**Comment by GtxFury** [comment]
提示: {"detail":"Could not parse your authentication token. Please try signing in again." 好的谢谢作者
