### ISSUE TITLE
希望镜像增加arm架构的构建

### ISSUE THREAD

**Issue by 12123ads** [Ink-Osier/PandoraToV1Api#17]
如题

**Comment by sumuen** [comment]
不懂就问，一个api请求的项目还会对架构有要求吗（

**Comment by 12123ads** [comment]
镜像这玩意，架构不同启动直接报错啊（


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月20日(周三) 凌晨1:34
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Ink-Osier/PandoraToV1Api] 希望镜像增加arm架构的构建 (Issue #17)




 
不懂就问，一个api请求的项目还会对架构有要求吗（
 
&mdash;

**Comment by xiaosaaaa** [comment]
dockerfile都有，学习一下自己build

**Comment by 12123ads** [comment]
> dockerfile都有，学习一下自己build

构建好了，能直接拉取还是方便（

**Comment by kenneth-mid** [comment]
> > dockerfile都有，学习一下自己build
> 
> 构建好了，能直接拉取还是方便（

能分享下吗? 学习下如何解决的,我手上也有一个这个的docker容器需求,因为我的备用服务器是arm的 现在跑步起来.

**Comment by 12123ads** [comment]
> > > dockerfile都有，学习一下自己build
> > 
> > 构建好了，能直接拉取还是方便（
> 
> 能分享下吗? 学习下如何解决的,我手上也有一个这个的docker容器需求,因为我的备用服务器是arm的 现在跑步起来.

学习学习dockerfile怎么用，直接让ChatGPT教你
