### ISSUE TITLE
RN vps 运行报错

### ISSUE THREAD

**Issue by spacex-3** [Ink-Osier/PandoraToV1Api#18]
不知道是不是python版本问题？

backend-to-api_1  | [2023-12-19 14:22:09 +0000] [8] [ERROR] Exception in worker process
backend-to-api_1  | Traceback (most recent call last):
backend-to-api_1  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
backend-to-api_1  |     worker.init_process()
backend-to-api_1  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/gthread.py", line 95, in init_process
backend-to-api_1  |     super().init_process()
backend-to-api_1  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 142, in init_process
backend-to-api_1  |     self.run()
backend-to-api_1  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/gthread.py", line 214, in run
backend-to-api_1  |     callback(key.fileobj)
backend-to-api_1  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/gthread.py", line 150, in on_client_socket_readable
backend-to-api_1  |     self.enqueue_req(conn)
backend-to-api_1  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/gthread.py", line 117, in enqueue_req
backend-to-api_1  |     fs = self.tpool.submit(self.handle, conn)
backend-to-api_1  |   File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 176, in submit
backend-to-api_1  |     self._adjust_thread_count()
backend-to-api_1  |   File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 199, in _adjust_thread_count
backend-to-api_1  |     t.start()
backend-to-api_1  |   File "/usr/local/lib/python3.9/threading.py", line 899, in start
backend-to-api_1  |     _start_new_thread(self._bootstrap, ())
backend-to-api_1  | RuntimeError: can't start new thread
backend-to-api_1  | [2023-12-19 14:22:09 +0000] [8] [INFO] Worker exiting (pid: 8)
backend-to-api_1  | [2023-12-19 14:22:09 +0000] [1] [ERROR] Worker (pid:8) exited with code 255
backend-to-api_1  | [2023-12-19 14:22:09 +0000] [1] [ERROR] Worker (pid:8) exited with code 255.
backend-to-api_1  | [2023-12-19 14:22:09 +0000] [11] [INFO] Booting worker with pid: 11

**Comment by Ink-Osier** [comment]
是不是服务器配置较低，看起来是资源不足导致的，后续版本可以考虑加一个允许自己配置开启的进程线程数的配置的地方，但是现在的配置也只是2个进程2个线程，其实并不高

**Comment by spacex-3** [comment]
哈哈哈好吧，我的vps性能是真的很差，那就还是在自己pve跑吧。主要是pandoranext部署在这台vps上面，想着把p2a也跑上去，就调用的时候是纯内网且图片upload地址不用涉及到家宽。
