### ISSUE TITLE
redis配置格式有点问题，报错service 'command' must be a mapping not a string.

### ISSUE THREAD

**Issue by Zephon-H** [Ink-Osier/PandoraToV1Api#19]
![image](https://github.com/Ink-Osier/PandoraToV1Api/assets/37538679/18cb839c-ce8d-428c-9e87-9d34b211377b)
redis配置格式有点问题，报错service 'command' must be a mapping not a string.需要修改缩进

**Comment by Ink-Osier** [comment]
oh不好意思，实际上没用redis，忘记删除了

**Comment by Ink-Osier** [comment]
已修复此问题，测试的时候写了忘了改了hh
