### ISSUE TITLE
哪些地方可以用内网地址 

### ISSUE THREAD

**Issue by superen7527** [Ink-Osier/PandoraToV1Api#20]
我的理解是用户不需要访问潘多拉，能访问这个项目api就好了。潘多拉甚至可以不放公网只内网让这个调用 但是看说明都是公网地址 有点奇怪 哪些可以填内网 这样延迟也低点。

**Comment by Ink-Osier** [comment]
如果本项目和潘多拉在同一个内网，潘多拉地址可以设定为内网地址，`UPLOAD_BASE_URL`需要你的用户可以访问到的本项目地址
