### ISSUE TITLE
能不能添加backend模式

### ISSUE THREAD

**Issue by superen7527** [Ink-Osier/PandoraToV1Api#21]
目前是全用proxy模式 但是像这种next调用又是用历史会话发送。其实希望可以优化一下 不走 <BaseURL>/v1/chat/completions 走<BaseURL>/backend-api/* 这样。然后处理一下用一个固定key后台刷新Accesstoken去请求。
现在这样也是用模拟对话模式 两种实际上都一样。但是现在这样反而记不住上下文。还要舍近求远压缩历史对话再发送 不如原来的聪明。

希望可以考虑一下 感谢。

**Comment by Ink-Osier** [comment]
没太懂，现在这个需要上下文直接传就行啊，可以记住上下文啊

**Comment by Ink-Osier** [comment]
和官方自己的v1没有任何区别啊

**Comment by Ink-Osier** [comment]
那可以关掉这个功能呀，你不想用的话

**Comment by Ink-Osier** [comment]
他会把所有历史都发给接口的

**Comment by Ink-Osier** [comment]
而且如果想用backend-api为什么不直接用PandoraNext，不是已经支持的很全面了么
