### ISSUE TITLE
希望可以提供一个不带prefix的选项，以兼容ninja proxy

### ISSUE THREAD

**Issue by cyx1322** [Ink-Osier/PandoraToV1Api#23]
Pandora很好，但是有次数限制，这就和不限次数的4-mobile很矛盾。
ninja本身没有限制，而且也提供backend api，用法一样，但没有prefix
[Ninja](https://github.com/gngpp/ninja/blob/main/doc/readme_zh.md)
希望可以设置一下检测到compose中prefix为空时，直接请求对应的URL

**Comment by Ink-Osier** [comment]
该功能已支持，请拉取最新版试用（最新版目录结构有所改变，请注意）

**Comment by assassinliujie** [comment]
> Pandora很好，但是有次数限制，这就和不限次数的4-mobile很矛盾。 ninja本身没有限制，而且也提供backend api，用法一样，但没有prefix [Ninja](https://github.com/gngpp/ninja/blob/main/doc/readme_zh.md) 希望可以设置一下检测到compose中prefix为空时，直接请求对应的URL

请问您是如何使用的呢，我这正常ninja的webui能对话，但是一用backend api就会报错

**Comment by cyx1322** [comment]
> > Pandora很好，但是有次数限制，这就和不限次数的4-mobile很矛盾。 ninja本身没有限制，而且也提供backend api，用法一样，但没有prefix [Ninja](https://github.com/gngpp/ninja/blob/main/doc/readme_zh.md) 希望可以设置一下检测到compose中prefix为空时，直接请求对应的URL
> 
> 请问您是如何使用的呢，我这正常ninja的webui能对话，但是一用backend api就会报错

你好，可以看一下你的日志吗，注意把敏感信息隐藏
