### ISSUE TITLE
建议增加是否删除会话的开关

### ISSUE THREAD

**Issue by volatile-static** [Ink-Osier/PandoraToV1Api#24]
留着不好吗

**Comment by Ink-Osier** [comment]
下周有时间可以加上

**Comment by volatile-static** [comment]
https://github.com/Ink-Osier/PandoraToV1Api/blob/fcdd99a1fc52ecc39207c22718c7106afb02aba2/main.py#L606
我看只需要在这判断一个环境变量就好了，要不我PR？

**Comment by Ink-Osier** [comment]
是的，但是现在环境变量实在太多了，我打算下周重构成配置文件，我下周统一改吧，因为还有bot模式很多需求也都需要加环境变量一类的控制参数

**Comment by Ink-Osier** [comment]
急用的话你可以先fork一个自己改一下

**Comment by volatile-static** [comment]
> 是的，但是现在环境变量实在太多了，我打算下周重构成配置文件，我下周统一改吧，因为还有bot模式很多需求也都需要加环境变量一类的控制参数

我的建议是用yaml做配置，一个config.yml加入gitignore，一个config.yml.example作为模板
