### ISSUE TITLE
项目成功启动，能发请求但是收不到返回

### ISSUE THREAD

**Issue by dashixiong-11** [Ink-Osier/PandoraToV1Api#25]
我使用的是chatgpt-next-web项目， 项目中的 环境变量OPENAI_API_KEY 是不是应该填 
>   <BaseURL>/fk 使用access token或session token，手动获取share token 
所获取的share token ？

**Comment by Ink-Osier** [comment]
填fk，以及请携带debug级日志提问谢谢

**Comment by dashixiong-11** [comment]
> 填fk，以及请携带debug级日志提问谢谢

弄好了 谢谢

**Comment by Ink-Osier** [comment]
👌🏻
