### ISSUE TITLE
希望大佬在这一行增加一个转字符串的语句，在面临消息内容为数组的时候计算token数量会出现抛错

### ISSUE THREAD

**Issue by biek12** [Ink-Osier/PandoraToV1Api#29]
<img width="1090" alt="image" src="https://github.com/Ink-Osier/PandoraToV1Api/assets/25276878/c4f312b8-330d-4dd4-a923-b13e374aa566">

**Comment by Ink-Osier** [comment]
好的，不好意思没考虑到gpt4v

**Comment by Ink-Osier** [comment]
已修复，请更新最新版

**Comment by biek12** [comment]
好的
