### ISSUE TITLE
返回格式上的一些问题

### ISSUE THREAD

**Issue by lvguanjun** [Ink-Osier/PandoraToV1Api#32]
pandoraNext 的 `/v1/chat/completions` 接口响应如下
```
b'data: {"id":"chatcmpl-oh0UFdq9cCceAKWoS4e3LyDxojf8V","object":"chat.completion.chunk","created":1703783665,"model":"gpt-4-32k","choices":[{"delta":{"role":"assistant"},"index":0,"finish_reason":null}]}\n\ndata: {"id":"chatcmpl-oh0UFdq9cCceAKWoS4e3LyDxojf8V","object":"chat.completion.chunk","created":1703783665,"model":"gpt-4-32k","choices":[{"delta":{"content":"Hello"},"index":0,"finish_reason":null}]}\n\ndata: {"id":"chatcmpl-oh0UFdq9cCceAKWoS4e3LyDxojf8V","object":"chat.completion.chunk","created":1703783665,"model":"gpt-4-32k","choices":[{"delta":{"content":"!"},"index":0,"finish_reason":null}]}\n\ndata: {"id":"chatcmpl-oh0UFdq9cCceAKWoS4e3LyDxojf8V","object":"chat.completion.chunk","created":1703783665,"model":"gpt-4-32k","choices":[{"delta":{"content":" How"},"index":0,"finish_reason":null}]}\n\ndata: {"id":"chatcmpl-oh0UFdq9cCceAKWoS4e3LyDxojf8V","object":"chat.completion.chunk","created":1703783665,"model":"gpt-4-32k","choices":[{"delta":{"content":" can"},"index":0,"finish_reason":null}]}\n\ndata: {"id":"chatcmpl-oh0UFdq9cCceAKWoS4e3LyDxojf8V","object":"chat.completion.chunk","created":1703783665,"model":"gpt-4-32k","choices":[{"delta":{"content":" I"},"index":0,"finish_reason":null}]}\n\ndata: {"id":"chatcmpl-oh0UFdq9cCceAKWoS4e3LyDxojf8V","object":"chat.completion.chunk","created":1703783665,"model":"gpt-4-32k","choices":[{"delta":{"content":" assist"},"index":0,"finish_reason":null}]}\n\ndata: {"id":"chatcmpl-oh0UFdq9cCceAKWoS4e3LyDxojf8V","object":"chat.completion.chunk","created":1703783665,"model":"gpt-4-32k","choices":[{"delta":{"content":" you"},"index":0,"finish_reason":null}]}\n\ndata: {"id":"chatcmpl-oh0UFdq9cCceAKWoS4e3LyDxojf8V","object":"chat.completion.chunk","created":1703783665,"model":"gpt-4-32k","choices":[{"delta":{"content":" today"},"index":0,"finish_reason":null}]}\n\ndata: {"id":"chatcmpl-oh0UFdq9cCceAKWoS4e3LyDxojf8V","object":"chat.completion.chunk","created":1703783665,"model":"gpt-4-32k","choices":[{"delta":{"content":"?"},"index":0,"finish_reason":null}]}\n\ndata: {"id":"chatcmpl-oh0UFdq9cCceAKWoS4e3LyDxojf8V","object":"chat.completion.chunk","created":1703783665,"model":"gpt-4-32k","choices":[{"delta":{},"index":0,"finish_reason":"stop"}]}\n\ndata: [DONE]\n\n'
```

本项目响应如下：
```
b'data:{"id": "chatcmpl-f0a45ac3f5f04e80aad66500c9be45fb", "object": "chat.completion.chunk", "created": 1703783102, "model": "gpt-4", "choices": [{"index": 0, "delta": {"content": ""}, "finish_reason": null}]}\n\ndata: {"id": "chatcmpl-f0a45ac3f5f04e80aad66500c9be45fb", "object": "chat.completion.chunk", "created": 1703783102, "model": "gpt-4", "choices": [{"index": 0, "delta": {"content": "Hello"}, "finish_reason": null}]}\n\ndata: {"id": "chatcmpl-f0a45ac3f5f04e80aad66500c9be45fb", "object": "chat.completion.chunk", "created": 1703783102, "model": "gpt-4", "choices": [{"index": 0, "delta": {"content": "!"}, "finish_reason": null}]}\n\ndata: {"id": "chatcmpl-f0a45ac3f5f04e80aad66500c9be45fb", "object": "chat.completion.chunk", "created": 1703783102, "model": "gpt-4", "choices": [{"index": 0, "delta": {"content": " How"}, "finish_reason": null}]}\n\ndata: {"id": "chatcmpl-f0a45ac3f5f04e80aad66500c9be45fb", "object": "chat.completion.chunk", "created": 1703783102, "model": "gpt-4", "choices": [{"index": 0, "delta": {"content": " can"}, "finish_reason": null}]}\n\ndata: {"id": "chatcmpl-f0a45ac3f5f04e80aad66500c9be45fb", "object": "chat.completion.chunk", "created": 1703783102, "model": "gpt-4", "choices": [{"index": 0, "delta": {"content": " I"}, "finish_reason": null}]}\n\ndata: {"id": "chatcmpl-f0a45ac3f5f04e80aad66500c9be45fb", "object": "chat.completion.chunk", "created": 1703783102, "model": "gpt-4", "choices": [{"index": 0, "delta": {"content": " assist"}, "finish_reason": null}]}\n\ndata: {"id": "chatcmpl-f0a45ac3f5f04e80aad66500c9be45fb", "object": "chat.completion.chunk", "created": 1703783102, "model": "gpt-4", "choices": [{"index": 0, "delta": {"content": " you"}, "finish_reason": null}]}\n\ndata: {"id": "chatcmpl-f0a45ac3f5f04e80aad66500c9be45fb", "object": "chat.completion.chunk", "created": 1703783102, "model": "gpt-4", "choices": [{"index": 0, "delta": {"content": " today"}, "finish_reason": null}]}\n\ndata: {"id": "chatcmpl-f0a45ac3f5f04e80aad66500c9be45fb", "object": "chat.completion.chunk", "created": 1703783102, "model": "gpt-4", "choices": [{"index": 0, "delta": {"content": "?"}, "finish_reason": null}]}\n\ndata: [DONE]\n\n'
```

可以发现相对于 pandoraNext 的接口，少了第一行关于 `"choices":[{"delta":{"role":"assistant"},"index":0,"finish_reason":null}]` 的响应，和最后一行关于 `"choices":[{"delta":{},"index":0,"finish_reason":"stop"}]` 的响应，在某些平台可能出错。

**Comment by lvguanjun** [comment]
整个花活
![Uploading 2bf52ced66f9b047ecff3574f6a504b.png…]()
![Uploading 2407a8ff7a6a57712a48794b8df60d0.png…]()
![Uploading 159850604130ee87d3516d98b1ebb21.png…]()

**Comment by Ink-Osier** [comment]
最新版已修复该问题，请升级最新版再试一下

**Comment by Ink-Osier** [comment]
> 整个花活
> 
> ![2bf52ced66f9b047ecff3574f6a504b](https://private-user-images.githubusercontent.com/58430934/293261494-be3797e2-5be4-4c2f-a918-f5b3a7146c92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM4MTQyNjksIm5iZiI6MTcwMzgxMzk2OSwicGF0aCI6Ii81ODQzMDkzNC8yOTMyNjE0OTQtYmUzNzk3ZTItNWJlNC00YzJmLWE5MTgtZjViM2E3MTQ2YzkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDAxMzkyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjNzYxMzE5MDk1YTI5ZGExZGRhNDZmMmY3NDg4ZDMwYjgzNDQzNGQzNDA1YTc1ZjViYzc5NTBlNDUwY2NlYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._fq-ajkXOtLrdTklngMiDNXOf3L7E9Gj_MoVaDCXvEc)
> 
> ![2407a8ff7a6a57712a48794b8df60d0](https://private-user-images.githubusercontent.com/58430934/293261520-450e2ca2-5a8c-445c-9d34-8459b2257a03.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM4MTQyNjksIm5iZiI6MTcwMzgxMzk2OSwicGF0aCI6Ii81ODQzMDkzNC8yOTMyNjE1MjAtNDUwZTJjYTItNWE4Yy00NDVjLTlkMzQtODQ1OWIyMjU3YTAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDAxMzkyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjNzA0OGU4MDMyOGVjYzQ4NmY4OGVjZjVmMzUyODM1NGExNmU1Y2YxNDQ2ZjU0Yjc1MWMwY2RkMjQ4YmNjZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Yw4S0b9YnMJpmb5ibmiSn75vxcrTorQcGFAH1BgFrMc)
> 
> ![159850604130ee87d3516d98b1ebb21](https://private-user-images.githubusercontent.com/58430934/293261558-f1b1d02d-b575-463b-80b1-848a9c784114.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM4MTQyNjksIm5iZiI6MTcwMzgxMzk2OSwicGF0aCI6Ii81ODQzMDkzNC8yOTMyNjE1NTgtZjFiMWQwMmQtYjU3NS00NjNiLTgwYjEtODQ4YTljNzg0MTE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDAxMzkyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3YzE5ZTUxMjVmOTE0NDNmM2MwNTE2ZDUwOTQ4Y2Y0MWZmNTk4NTczMDMwYjRlNTY4NGVjZTU5ODU4MzBhMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2ufxTBuxrAbHR2TIu8Ezs2-bRQ1NMLLgahqyDj1ivmU)

酷
