### ISSUE TITLE
请问线程数的两个变量设置有什么用？

### ISSUE THREAD

**Issue by suyunkai** [Ink-Osier/PandoraToV1Api#34]
是否需要设置啊？目前我用下来，感觉有时候并发多好像会不回复，重启一下容器就好了，是否和没有设置线程数有关？

**Comment by Ink-Osier** [comment]
有可能，不过主要和你设置的进程数有关，这个基本就是进程数你设置为多少同时就能响应多少个请求，如果你没设置默认也是有的，默认是1进程2线程

**Comment by suyunkai** [comment]
额，所以需要设置的话，我应该怎么调整呀。比如我想保证至少3个并发。是设置3进程3线程，还是1进程3线程即可。

**Comment by Ink-Osier** [comment]
至少3进程2线程
