### ISSUE TITLE
大佬，在请求dalle3的时候，url不可以直接返回吗？

### ISSUE THREAD

**Issue by CCzhiyun** [Ink-Osier/PandoraToV1Api#35]

**Comment by Ink-Osier** [comment]
现在不是和官方的dalle接口响应基本一致么

**Comment by CCzhiyun** [comment]
我才你说的是我应该直接把model设为dall-e-3，我猜应该是因为我现在用的是gpt-4-s，所以他这么返回，大佬问问另外一个问题，这个key_for_gpts_info是这样填写么，我好像请求不了
![image](https://github.com/Ink-Osier/PandoraToV1Api/assets/19650742/011652ae-88fd-4701-bb04-c30fe0887628)

**Comment by Ink-Osier** [comment]
> 我才你说的是我应该直接把model设为dall-e-3，我猜应该是因为我现在用的是gpt-4-s，所以他这么返回，大佬问问另外一个问题，这个key_for_gpts_info是这样填写么，我好像请求不了 ![image](https://private-user-images.githubusercontent.com/19650742/293340931-011652ae-88fd-4701-bb04-c30fe0887628.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NDMxNjcsIm5iZiI6MTcwMzg0Mjg2NywicGF0aCI6Ii8xOTY1MDc0Mi8yOTMzNDA5MzEtMDExNjUyYWUtODhmZC00NzAxLWJiMDQtYzMwZmUwODg3NjI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDA5NDEwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmZWJiZDkwNDQ5MTExZDNkMTI1YTU3ZDgyNThiM2MxMGYxOTA0Mzg4NjJlOWIwNDg0ZjIxMWI1ZTUzMTFmOTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iiexeY_u7MUM4fYS7kRBVtFP5Oa-Qdxlc15Y0FLNB1o)

没太看懂你的意思但是能解决就行，你这个key写的不对，这个参数应该是一个pandoranext的fk才对

**Comment by CCzhiyun** [comment]
其实我的意思是我请求了dall-e-3，response是以下这样，不知道data下面的url可不可以返回官网他自己的地址呢
{
    "created": 1703843482,
    "data": [
        {
            "url": "https://公网ip:端口/images/image_20231229095121.png"
        }
    ],
    "reply": "\n```\n{\"prompt\":\"A serene white cat with bright blue eyes, sitting gracefully in a sunlit room with light filtering through sheer curtains. The cat's fur is fluffy and well-groomed, giving it an elegant and majestic look. The room is tastefully decorated, with a comfortable armchair and a small side table with a vase of fresh flowers.\",\"size\":\"1024x1024\"}Here is the image of a serene white cat with bright blue eyes, sitting gracefully in a sunlit room."
}
![image](https://github.com/Ink-Osier/PandoraToV1Api/assets/19650742/f96229d3-34d3-40a9-8afe-3d2742793245)

**Comment by Ink-Osier** [comment]
噢噢，可以是可以，但是这样设计也是因为用这个主要是大家想用在各种国内客户端，用自己的域名可以以防什么时候openai这个域名被墙

**Comment by CCzhiyun** [comment]
因为dall-e-3的api就是就是返回一个url地址，不过这样设计也是可以，就是用习惯了官网api的要改一下代码了，哈哈哈哈

**Comment by Ink-Osier** [comment]
🤔还是没太懂有什么区别，不是只有链接地址不一样嘛，你是直接写死了前边的域名然后解析每次的文件id去获取图片的嘛

**Comment by CCzhiyun** [comment]
> 🤔还是没太懂有什么区别，不是只有链接地址不一样嘛，你是直接写死了前边的域名然后解析每次的文件id去获取图片的嘛

其实如果你直接扔地址回来给我们，我们就直接扔回给前端，啥都不用做处理，哈哈哈哈

**Comment by Ink-Osier** [comment]
> > 🤔还是没太懂有什么区别，不是只有链接地址不一样嘛，你是直接写死了前边的域名然后解析每次的文件id去获取图片的嘛
> 
> 其实如果你直接扔地址回来给我们，我们就直接扔回给前端，啥都不用做处理，哈哈哈哈

依然没懂和现在有什么区别，现在不就是么

**Comment by Ink-Osier** [comment]
如果想要官网的链接现在也已经支持了

**Comment by CCzhiyun** [comment]
> 如果想要官网的链接现在也已经支持了

真的么，我应该怎么做才可以更新最新的呢

**Comment by Ink-Osier** [comment]
看一下更新日志，新增了一个参数，你加上去然后拉最新的镜像就可以了

**Comment by CCzhiyun** [comment]
> 看一下更新日志，新增了一个参数，你加上去然后拉最新的镜像就可以了

感谢感谢，我去试一下
