### ISSUE TITLE
关于need_delete_conversation_after_response

### ISSUE THREAD

**Issue by spacex-3** [Ink-Osier/PandoraToV1Api#37]
我设置了false后想看看记录长啥样，我用的微信机器人

然后我跟机器人发了两次指令（间隔1分钟不到）结果在pandora web ui里面显示是两个new chat。
第一个是第一句对话。第二个chat是有两句对话。也就意味着这样子的话是重复了第一句对话？这样对于额度的消耗是否不断重复了？不知道是机器人设置的问题还是。。

<img width="866" alt="image" src="https://github.com/Ink-Osier/PandoraToV1Api/assets/84770364/72e99478-1343-43ed-9635-71120fe8b0eb">
<img width="1043" alt="image" src="https://github.com/Ink-Osier/PandoraToV1Api/assets/84770364/9bca8197-fcf2-427a-a557-0544102d5190">

**Comment by Ink-Osier** [comment]
这是正常的，不会重复消耗额度，要实现上下文需要将上下文一起传回而且会话id随机生成才会这样的，不过欢迎帮忙再测试一下~
