### ISSUE TITLE
大佬，加了这个感觉没用哇

### ISSUE THREAD

**Issue by CCzhiyun** [Ink-Osier/PandoraToV1Api#38]
![image](https://github.com/Ink-Osier/PandoraToV1Api/assets/19650742/31419f58-b47a-42d6-bbb2-fd9e0589828c)

**Comment by CCzhiyun** [comment]
还是没有显示完整路径

**Comment by Ink-Osier** [comment]
什么完整路径，这个是使用openai域名的，和路径没关系呀

**Comment by CCzhiyun** [comment]
> 什么完整路径，这个是使用openai域名的，和路径没关系呀

抱歉我没讲清楚，就是想说没返回openai域名的图片

**Comment by Ink-Osier** [comment]
日志还有没显示的现象发一下

**Comment by CCzhiyun** [comment]
不好意思，是我没更新镜像导致
