### ISSUE TITLE
需要pandora的license id吗？

### ISSUE THREAD

**Issue by 14790897** [Ink-Osier/PandoraToV1Api#4]

**Comment by Ink-Osier** [comment]
不需要，只需要调用已经部署好的 Pandora-Next

**Comment by 14790897** [comment]
这怎么做到的？是向秦始皇申请特权了？

Wizerd ***@***.***> 于 2023年12月15日周五 下午5:37写道：

**Comment by Ink-Osier** [comment]
其实你自己用postman、curl之类的仿照我代码里的请求也可以直接调用，我只是做了个封装和格式统一而已

**Comment by 14790897** [comment]
哦，知道了，我搞错了
