### ISSUE TITLE
请问能否实现直接读取图片或文件的外链 然后实现上传文件

### ISSUE THREAD

**Issue by GtxFury** [Ink-Osier/PandoraToV1Api#40]
因为很多老的程序还不支持上传文件或者图片的功能，如果可以的话老的程序也可以变相上传文件。感谢

**Comment by Ink-Osier** [comment]
不能，不知道你的外链是在prompt的哪个部分，你可以试试让gpt直接用bing访问一下你的链接

**Comment by Ink-Osier** [comment]
是可以，但是没有做这个的计划不好意思，如果有需要可以fork本项目自己加一下，因为并不是每条消息都携带url，这样会大幅加大pandora额度的消耗

**Comment by GtxFury** [comment]
没有关系，只是提个意见，毕竟是小众需求，谢谢作者

**Comment by Ink-Osier** [comment]
> 没有关系，只是提个意见，毕竟是小众需求，谢谢作者

嗯嗯没事的，也是帮助项目发展~

**Comment by GtxFury** [comment]
看到某家api中转有类似功能 提供个思路 [](文件链接) 可以只识别固定的提示词前缀来实现，这样也算是不错的解决方案

**Comment by GtxFury** [comment]
看到某家中转有类似的功能 可以提供一个思路 [](文件链接)这样也是个不错的解决方案

**Comment by GtxFury** [comment]
看到某家中转有类似的功能 可以按照特定的提示词格式来识别文件 比如说*（文件链接） 这样也是一种不错的解决思路

**Comment by Ink-Osier** [comment]
> 看到某家中转有类似的功能 可以按照特定的提示词格式来识别文件 比如说*（文件链接） 这样也是一种不错的解决思路

嗯是有的，我之前在其他项目也实现过，但是相对还是太小众的需求了，还是gpt-4-vision这种未来才是主流
