### ISSUE TITLE
请问图片链接获取不全是什么原因？

### ISSUE THREAD

**Issue by volatile-static** [Ink-Osier/PandoraToV1Api#43]
![image](https://github.com/Ink-Osier/PandoraToV1Api/assets/59945270/2deedb8a-e03e-48cb-b2c0-3dfac0053f47)
![image](https://github.com/Ink-Osier/PandoraToV1Api/assets/59945270/fe93e1db-adba-428d-8ac5-786e9ba80614)

**Comment by Ink-Osier** [comment]
这个确定不是控制台自己缩减的么，在网页或者日志里看看具体获取到的链接是什么呢

**Comment by volatile-static** [comment]
还真是控制台的问题，感谢大佬指点！
