### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by 12123ads** [Ink-Osier/PandoraToV1Api#44]
这个可以支持tool calls吗？现在用不了类似lobechat那样的插件

**Comment by Ink-Osier** [comment]
还不支持，核心还是把官网chat2api，而且现在有插件比官网网页的插件厉害了么

**Comment by 12123ads** [comment]
并不是，只是没钱上plus，这样能嫖一下3.5（


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月8日(周一) 上午7:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Ink-Osier/PandoraToV1Api] 请教一个问题 (Issue #44)




 
还不支持，核心还是把官网chat2api，而且现在有插件比官网网页的插件厉害了么
 
&mdash;
