### ISSUE TITLE
使用curl无法联通

### ISSUE THREAD

**Issue by Payne-Wang** [Ink-Osier/PandoraToV1Api#46]
## 使用ToV1api+使用gpt-3.5-turbo模型
curl http://ToV1api_url:50011/v1/chat/completions  -H "Content-Type: application/json"  -H "Authorization: Bearer fk-*****"  -d '{ "model": "gpt-3.5-turbo", "messages": [{"role": "system","content": "You are a helpful assistant."},{"role": "user","content": "Hello!"}]}'

```
<!doctype html>
<html lang=en>
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```

## 使用ToV1api+使用gpt-4模型
curl http://ToV1api_url:50011/v1/chat/completions  -H "Content-Type: application/json"  -H "Authorization: Bearer fk-*****"  -d '{ "model": "gpt-4", "messages": [{"role": "system","content": "You are a helpful assistant."},{"role": "user","content": "Hello!"}]}'

```
{"error":"model is not accessible"}
```

另外，我将生成的sharetoken放到one-api里面，渠道API地址设置成http://ToV1api_url:50011，也无法使用。

请问该如何写请求，以使用gpt-4-s、gpt-4-mobile这几个模型？谢谢大佬

**Comment by Ink-Osier** [comment]
请提供脱敏后的debug日志以及配置文件

**Comment by Payne-Wang** [comment]
谢谢大佬！
## 这个是调用gpt-3.5-turbo的日志文件
![image](https://github.com/Ink-Osier/PandoraToV1Api/assets/44337721/b82619e8-f27a-4d1a-8bb1-924684c60587)
## 这个是我的配置
![image](https://github.com/Ink-Osier/PandoraToV1Api/assets/44337721/fe5d57af-9799-4e93-8a29-e7333a6a125b)

## 这个是pandoranext的配置
![image](https://github.com/Ink-Osier/PandoraToV1Api/assets/44337721/49f091e7-d477-4759-83da-ac2eb9a61ab8)

**Comment by Ink-Osier** [comment]
pandora_base_url这个配置是不是没写http或者https

**Comment by Payne-Wang** [comment]
> pandora_base_url这个配置是不是没写http或者https

牛逼老哥，可以用了，谢谢
