### ISSUE TITLE
请教下关于上下文的问题

### ISSUE THREAD

**Issue by lin-z-z** [Ink-Osier/PandoraToV1Api#47]
大佬你好，我使用l微信机器人，微信机器人项目地址为：https://github.com/zhayujie/chatgpt-on-wechat/tree/master,
我想请问下的是我设置了该项目中在群聊中开启同一个会话然后保证上下文，但是实际过程中，他会打开多个窗口进行提问，如下所示，
![image](https://github.com/Ink-Osier/PandoraToV1Api/assets/75935186/f3580769-1f21-4570-aa46-d1a9c5704b49)
我的config.json如下:
```json
{
    "log_level": "ERROR",
    "need_log_to_file": "true",
    "process_workers": 2,
    "process_threads": 2,
    "pandora_base_url": "http://10.0.8.8:8181",
    "pandora_api_prefix": "tokensTool01",
    "backend_container_url": "http://10.0.8.8:50011",
    "backend_container_api_prefix": "",
    "key_for_gpts_info": "fk-***",
    "gpt_4_s_new_name": "gpt-4-s,gpt-4",
    "gpt_4_mobile_new_name": "gpt-4-mobile,dall-e-3",
    "gpt_3_5_new_name": "gpt-3.5-turbo",
    "need_delete_conversation_after_response": "false",
    "use_oaiusercontent_url": "false",
    "use_pandora_file_server": "true",
    "custom_arkose_url": "false",
    "arkose_urls": "",
    "dalle_prompt_prefix": "请严格根据我的以下要求完成绘图任务，如果我没有发出指定的绘画指令，则绘制出我发出的文字对应的图片：",
    "bot_mode": {
        "enabled": "true",
        "enabled_markdown_image_output": "true",
        "enabled_plain_image_url_output": "true",
        "enabled_bing_reference_output": "false",
        "enabled_plugin_output": "false"
    }
}
```
我在微信项目中的配置地址为http://10.0.8.8:50011/v1，传入的model名称为gpt-4，是可以调用的，但是同一个群聊会一直新增窗口，想知道是不是哪里配置不对导致没有在同一个会话窗口中

**Comment by sumuen** [comment]
每次请求就等于**新开**一个会话，连续对话的实现是把历史会话也附加到当前会话中并创建一个新的会话，而不是在web端的会话中的连续对话。

想要实现Web端会话中的连续会话，需要两个额外的信息，**会话id**与上一条**信息的ID**，会话id在每次新建会话时会随机生成，上一条信息id则在上一条会话请求的响应中，因为在openai的官方请求格式中，并没有这两个数据，所以依靠官方api格式实现web端的连续对话是困难的，两种方式输出结果也没有差异,

如果要实现可以[参考](https://github.com/transitive-bullshit/chatgpt-api/blob/main/src/chatgpt-unofficial-proxy-api.ts)](https://github.com/transitive-bullshit/chatgpt-api/blob/main/src/chatgpt-unofficial-proxy-api.ts)

**Comment by lin-z-z** [comment]
> 每次请求就等于**新开**一个会话，连续对话的实现是把历史会话也附加到当前会话中并创建一个新的会话，而不是在web端的会话中的连续对话。
> 
> 想要实现Web端会话中的连续会话，需要两个额外的信息，**会话id**与上一条**信息的ID**，会话id在每次新建会话时会随机生成，上一条信息id则在上一条会话请求的响应中，因为在openai的官方请求格式中，并没有这两个数据，所以依靠官方api格式实现web端的连续对话是困难的，两种方式输出结果也没有差异,
> 
> 如果要实现可以[[参考](https://github.com/transitive-bullshit/chatgpt-api/blob/main/src/chatgpt-unofficial-proxy-api.ts)](https://github.com/transitive-bullshit/chatgpt-api/blob/main/src/chatgpt-unofficial-proxy-api.ts)

好的，谢谢大佬，我研究下
