### ISSUE TITLE
如果在输出过程中被中断，在web端的对话记录不会被删除

### ISSUE THREAD

**Issue by Payne-Wang** [Ink-Osier/PandoraToV1Api#48]
如题，这样可能会在共享账号中泄露隐私

**Comment by Ink-Osier** [comment]
后续版本会进行优化

**Comment by Ink-Osier** [comment]
你这个被中断的情况可以给我一份日志么，我来复现一下问题

**Comment by Ink-Osier** [comment]
待会可以试试0.4.9版本的，优化了异常处理，看看还会不会出现这个问题（我感觉是难免的，偶尔出现不稳定的）。如果还是很多次后边会考虑多开一个服务定期检测删除失败的会话记录自动删除。

**Comment by Payne-Wang** [comment]
不好意思，刚下班。

我太清楚你需要的是哪部分的日志文件，不过从我使用的体验上看，这个bug是一直有的，每次都可以重现。

我觉得这个程序的处理逻辑是，当openai完整返回信息后，会执行删除会话操作。

这bug会在两种中断会话的情况下出现：

1、如果回复的信息较短，我在流式还未输出完时中断会话，虽然在app上显示会话被中断，但是后台实际上已经完全输出了回复的信息，并且执行了删除会话操作，但是实际上在web端会话并未被删除。如下图（该图虽然后台输出了删除会话的日志，但实际上web并没有删除会话！）
![image](https://github.com/Ink-Osier/PandoraToV1Api/assets/44337721/a0b16ee2-a801-4ab5-a5e9-dc20ab52f5fb)

2、如果回复的信息很长，同样在输出时中断会话，此时app和后台都显示会话被中断，但是因为后台没有输出完，所以没有执行删除会话，同样的，在web端会话并未被删除。如下图
![image](https://github.com/Ink-Osier/PandoraToV1Api/assets/44337721/a40cb7a5-0290-409a-9704-9fabc75b5950)

我觉得第一种情况更容易被忽略，请您注意！

是否有可能在输出结果的整个过程都不产生会话，我记得上一版本的pandora是可以做到的。

**Comment by Ink-Osier** [comment]
> 不好意思，刚下班。
> 
> 我太清楚你需要的是哪部分的日志文件，不过从我使用的体验上看，这个bug是一直有的，每次都可以重现。
> 
> 我觉得这个程序的处理逻辑是，当openai完整返回信息后，会执行删除会话操作。
> 
> 这bug会在两种中断会话的情况下出现：
> 
> 1、如果回复的信息较短，我在流式还未输出完时中断会话，虽然在app上显示会话被中断，但是后台实际上已经完全输出了回复的信息，并且执行了删除会话操作，但是实际上在web端会话并未被删除。如下图（该图虽然后台输出了删除会话的日志，但实际上web并没有删除会话！） ![image](https://private-user-images.githubusercontent.com/44337721/295555980-a0b16ee2-a801-4ab5-a5e9-dc20ab52f5fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMDIwNjIsIm5iZiI6MTcwNTMwMTc2MiwicGF0aCI6Ii80NDMzNzcyMS8yOTU1NTU5ODAtYTBiMTZlZTItYTgwMS00YWI1LWE1ZTktZGMyMGFiNTJmNWZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDA2NTYwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxNGE3OGUwMDBhMDM2ZTQ2MjQ1MzQ5NmJiNWZjNGNmYzhlNTAxMTk2MmM0ZmI3NmMxOTUxOTgzOWFmNzZjYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ELc3Sth1wyzzr9B088eNCVbUC18BwM81QdxD6JUrHeY)
> 
> 2、如果回复的信息很长，同样在输出时中断会话，此时app和后台都显示会话被中断，但是因为后台没有输出完，所以没有执行删除会话，同样的，在web端会话并未被删除。如下图 ![image](https://private-user-images.githubusercontent.com/44337721/295557468-a40cb7a5-0290-409a-9704-9fabc75b5950.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMDIwNjIsIm5iZiI6MTcwNTMwMTc2MiwicGF0aCI6Ii80NDMzNzcyMS8yOTU1NTc0NjgtYTQwY2I3YTUtMDI5MC00MDlhLTk3MDQtOWZhYmM3NWI1OTUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDA2NTYwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1YzFhYTc2MGQwMDdkNjY4NTJiM2NhY2IwNTIyYzMzODJjZmZhODZmODgyYjY0YmFhNTg4NzRiODc3ZjRmZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RESUeiEjgtzLk2dTDaYGxa5uPuTGzNNYD6aGcmaoM6E)
> 
> 我觉得第一种情况更容易被忽略，请您注意！
> 
> 是否有可能在输出结果的整个过程都不产生会话，我记得上一版本的pandora是可以做到的。

第一个问题的话我这边测试实际上是可以正常删除的，如果你的实际上没有被删除可能是你在消息回复过程中打开了网页端pandora，然后后台删除会话记录后也没有刷新页面导致的，此时这个会话也是点不开的，刷新后该会话就会消失了。针对第二个问题暂时还没有出现过，如果我这边可以复现会针对性进行修复。

**Comment by Payne-Wang** [comment]
> 是否有可能在输出结果的整个过程都不产生会话，我记得上一版本的pandora是可以做到的。

好的，感谢留意。另外请问是否有可能在输出结果的整个过程都不产生会话，我记得上一版本的pandora是可以做到的。

**Comment by Ink-Osier** [comment]
> > 是否有可能在输出结果的整个过程都不产生会话，我记得上一版本的pandora是可以做到的。
> 
> 好的，感谢留意。另外请问是否有可能在输出结果的整个过程都不产生会话，我记得上一版本的pandora是可以做到的。

经过测试好像确实可以，等我待会推一个版本

**Comment by Payne-Wang** [comment]
> > > 是否有可能在输出结果的整个过程都不产生会话，我记得上一版本的pandora是可以做到的。
> > 
> > 
> > 好的，感谢留意。另外请问是否有可能在输出结果的整个过程都不产生会话，我记得上一版本的pandora是可以做到的。
> 
> 经过测试好像确实可以，等我待会推一个版本

好的，期待你的新版本，感谢

**Comment by Ink-Osier** [comment]
> > > > 是否有可能在输出结果的整个过程都不产生会话，我记得上一版本的pandora是可以做到的。
> > > 
> > > 
> > > 好的，感谢留意。另外请问是否有可能在输出结果的整个过程都不产生会话，我记得上一版本的pandora是可以做到的。
> > 
> > 
> > 经过测试好像确实可以，等我待会推一个版本
> 
> 好的，期待你的新版本，感谢

最新版已支持，全程不会出现记录了

**Comment by Payne-Wang** [comment]
> > > > > 是否有可能在输出结果的整个过程都不产生会话，我记得上一版本的pandora是可以做到的。
> > > > 
> > > > 
> > > > 好的，感谢留意。另外请问是否有可能在输出结果的整个过程都不产生会话，我记得上一版本的pandora是可以做到的。
> > > 
> > > 
> > > 经过测试好像确实可以，等我待会推一个版本
> > 
> > 
> > 好的，期待你的新版本，感谢
> 
> 最新版已支持，全程不会出现记录了

太棒了！

**Comment by Payne-Wang** [comment]
> > > > > 是否有可能在输出结果的整个过程都不产生会话，我记得上一版本的pandora是可以做到的。
> > > > 
> > > > 
> > > > 好的，感谢留意。另外请问是否有可能在输出结果的整个过程都不产生会话，我记得上一版本的pandora是可以做到的。
> > > 
> > > 
> > > 经过测试好像确实可以，等我待会推一个版本
> > 
> > 
> > 好的，期待你的新版本，感谢
> 
> 最新版已支持，全程不会出现记录了

刚才试了一下，似乎还是会产生中间记录。
我是直接
```
docker-compose down
git pull
docker-compose up -d
```
这样子更新的，而且修改的python文件也更新了，但是仍会出现中间记录。

**Comment by Ink-Osier** [comment]
> > > > > > 是否有可能在输出结果的整个过程都不产生会话，我记得上一版本的pandora是可以做到的。
> > > > > 
> > > > > 
> > > > > 好的，感谢留意。另外请问是否有可能在输出结果的整个过程都不产生会话，我记得上一版本的pandora是可以做到的。
> > > > 
> > > > 
> > > > 经过测试好像确实可以，等我待会推一个版本
> > > 
> > > 
> > > 好的，期待你的新版本，感谢
> > 
> > 
> > 最新版已支持，全程不会出现记录了
> 
> 刚才试了一下，似乎还是会产生中间记录。 我是直接
> 
> ```
> docker-compose down
> git pull
> docker-compose up -d
> ```
> 
> 这样子更新的，而且修改的python文件也更新了，但是仍会出现中间记录。

看一下启动的时候的版本号，估计是你拉的时候自动构建镜像还没完成吧，重新再拉一下试试

**Comment by Payne-Wang** [comment]
可以了，看了日志确实修复了，感谢！
