### ISSUE TITLE
有没有考虑过定期刷新FK？

### ISSUE THREAD

**Issue by biek12** [Ink-Osier/PandoraToV1Api#50]
fk这个我每次都需要手动去刷新确实有些繁琐

**Comment by biek12** [comment]
给一个门呢，我去瞅瞅，待会儿你帮我合一个Readme

**Comment by Ink-Osier** [comment]
> 给一个门呢，我去瞅瞅，待会儿你帮我合一个Readme

这里：https://github.com/nianhua99/PandoraNext-Helper
