### ISSUE TITLE
风控最近收紧了？

### ISSUE THREAD

**Issue by assassinliujie** [Ink-Osier/PandoraToV1Api#53]
2024-01-19 03:06:54 2024-01-18 19:06:54,820 [DEBUG] - message 为空: data_json: {'message': None, 'conversation_id': 'fee775d8-423e-4260-8cf2-bf9bf2c0826d', 'error': 'Our systems have detected unusual activity from your system. Please try again later.'}
2024-01-19 03:06:54 2024-01-18 19:06:54,822 [ERROR] - Exception: 'NoneType' object has no attribute 'get'
2024-01-19 03:06:54 2024-01-18 19:06:54,823 [INFO] - 会话结束
2024-01-19 03:06:54 2024-01-18 19:06:54,824 [INFO] - 完整消息: 
2024-01-19 03:06:54 2024-01-18 19:06:54,826 [DEBUG] - 会话结束-外层
2024-01-19 03:06:55 2024-01-18 19:06:55,821 [DEBUG] - 接受到停止信号，停止保活线程
这估计就是真风控了

**Comment by Ink-Osier** [comment]
> 2024-01-19 03:06:[54 2024-01-18](tel:54 2024-01-18) 19:06:54,820 [DEBUG] - message 为空: data_json: {'message': None, 'conversation_id': 'fee775d8-423e-4260-8cf2-bf9bf2c0826d', 'error': 'Our systems have detected unusual activity from your system. Please try again later.'} 2024-01-19 03:06:[54 2024-01-18](tel:54 2024-01-18) 19:06:54,822 [ERROR] - Exception: 'NoneType' object has no attribute 'get' 2024-01-19 03:06:[54 2024-01-18](tel:54 2024-01-18) 19:06:54,823 [INFO] - 会话结束 2024-01-19 03:06:[54 2024-01-18](tel:54 2024-01-18) 19:06:54,824 [INFO] - 完整消息: 2024-01-19 03:06:[54 2024-01-18](tel:54 2024-01-18) 19:06:54,826 [DEBUG] - 会话结束-外层 2024-01-19 03:06:[55 2024-01-18](tel:55 2024-01-18) 19:06:55,821 [DEBUG] - 接受到停止信号，停止保活线程 这估计就是真风控了

貌似是始皇的arkose出问题了

**Comment by goxofy** [comment]
我也是这个提示

**Comment by assassinliujie** [comment]
> > 2024-01-19 03:06:[54 2024-01-18](tel:54 2024-01-18) 19:06:54,820 [DEBUG] - message 为空: data_json: {'message': None, 'conversation_id': 'fee775d8-423e-4260-8cf2-bf9bf2c0826d', 'error': 'Our systems have detected unusual activity from your system. Please try again later.'} 2024-01-19 03:06:[54 2024-01-18](tel:54 2024-01-18) 19:06:54,822 [ERROR] - Exception: 'NoneType' object has no attribute 'get' 2024-01-19 03:06:[54 2024-01-18](tel:54 2024-01-18) 19:06:54,823 [INFO] - 会话结束 2024-01-19 03:06:[54 2024-01-18](tel:54 2024-01-18) 19:06:54,824 [INFO] - 完整消息: 2024-01-19 03:06:[54 2024-01-18](tel:54 2024-01-18) 19:06:54,826 [DEBUG] - 会话结束-外层 2024-01-19 03:06:[55 2024-01-18](tel:55 2024-01-18) 19:06:55,821 [DEBUG] - 接受到停止信号，停止保活线程 这估计就是真风控了
> 
> 貌似是始皇的arkose出问题了

自己处理arkose能缓解不

**Comment by assassinliujie** [comment]
> > > > 2024-01-19 03:06:[54 2024-01-18](tel:[54 2024-01-18](tel:54 2024-01-18)) 19:06:54,820 [DEBUG] - message 为空: data_json: {'message': None, 'conversation_id': 'fee775d8-423e-4260-8cf2-bf9bf2c0826d', 'error': 'Our systems have detected unusual activity from your system. Please try again later.'} 2024-01-19 03:06:[54 2024-01-18](tel:[54 2024-01-18](tel:54 2024-01-18)) 19:06:54,822 [ERROR] - Exception: 'NoneType' object has no attribute 'get' 2024-01-19 03:06:[54 2024-01-18](tel:[54 2024-01-18](tel:54 2024-01-18)) 19:06:54,823 [INFO] - 会话结束 2024-01-19 03:06:[54 2024-01-18](tel:[54 2024-01-18](tel:54 2024-01-18)) 19:06:54,824 [INFO] - 完整消息: 2024-01-19 03:06:[54 2024-01-18](tel:[54 2024-01-18](tel:54 2024-01-18)) 19:06:54,826 [DEBUG] - 会话结束-外层 2024-01-19 03:06:[55 2024-01-18](tel:[55 2024-01-18](tel:55 2024-01-18)) 19:06:55,821 [DEBUG] - 接受到停止信号，停止保活线程 这估计就是真风控了
> > > 
> > > 
> > > 貌似是始皇的arkose出问题了
> > 
> > 
> > 自己处理arkose能缓解不
> 
> 现在Pandora已经修复了，可以再试试，不过有能力的话也建议自己弄一个arkose服务保底

好了半天之后今天早上起来又挂了，我看看先自建一个试试
