### ISSUE TITLE
key_for_gpts_info参数是否可以不提供

### ISSUE THREAD

**Issue by Payne-Wang** [Ink-Osier/PandoraToV1Api#58]
大佬，key_for_gpts_info这个参数根据文档说明，需要为gpts额外提供一个token，但是pandora关闭后，无法使用可以自动更新的fk，只能用10天有效期的access token，这样就需要每隔十天手动更新key_for_gpts_info。

这个参数是否可以手动关闭，比如设置一个use_key_for_gpts_info逻辑参数，当为true时，可以使用key_for_gpts_info，如果为false时，key_for_gpts_info参数失效。谢谢大佬！

**Comment by Ink-Osier** [comment]
等我有空推个支持缓存gpts配置的版本上来吧，之前一直本地用的这个功能，没推上来

**Comment by Ink-Osier** [comment]
0.7.5版本支持缓存了，只要获取过一次gpts配置后边这个你填在config里的token过期了也没事，会自动使用缓存的token

**Comment by Payne-Wang** [comment]
感谢大佬！
