### ISSUE TITLE
希望增加上传图片的功能

### ISSUE THREAD

**Issue by cyx1322** [Ink-Osier/PandoraToV1Api#7]
GPT-4 和 GPT-4-Mobile 都有上传图片的功能，希望作者增加backend转vision api的功能，这样能对接一些支持多模态的gpt web，例如lobechat。
参考：[https://platform.openai.com/docs/guides/vision](https://platform.openai.com/docs/guides/vision)

**Comment by zhushen12580** [comment]
蹲一个

**Comment by Ink-Osier** [comment]
该功能已支持，请关注最新版项目，测试过的客户端较少，如果有什么问题大家再发新的issue吧~
