### ISSUE TITLE
绘图功能要开通plus用户吗？普通用户能否使用 

### ISSUE THREAD

**Issue by ambertear** [Ink-Osier/PandoraToV1Api#8]
绘图功能要开通plus用户吗？普通用户能否使用 
![QQ截图20231216134614](https://github.com/Ink-Osier/PandoraToV1Api/assets/219572/8d7c55a1-92ef-4dd3-8d53-1ef868386fca)

**Comment by Ink-Osier** [comment]
需要，除了3.5以外所有功能均需要开通plus
